In [8]:
data = [1, 2, 3, 4]
result = []
result2 = []

for i in data:
    result2.append(i * 10)
    
print(result2)

[10, 20, 30, 40]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr = arr * 10

print(arr)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3]) # python list type을 numpy의 ndarray 형식으로 생성

print(type(arr))

In [11]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim) # 차원 출력 -> 2차원 배열이므로 '2' 출력
print(arr.shape) # 배열 구조 출력

2


In [13]:
import numpy as np

arr = np.arange(5)
print(arr)

arr = np.arange(5, 15, 2) # 5 ~ 14까지 2씩 증가
print(arr)

arr1 = np.arange(5, 10) # 5 ~ 9까지 1씩 증가
print(arr1)

[0 1 2 3 4]


In [ ]:
np.array # 함수 원형 확인 shift + Tab

In [15]:
arr = np.zeros(5)  # numpy의 ndarray를 0으로 초기화하여 생성
print(arr)

[0. 0. 0. 0. 0.]


In [23]:
arr = np.zeros((2, 5)) # 2 x 5 형태의 ndarray 생성
print(arr)
print(arr.ndim)

print('\n')

arr = np.zeros((2, 2, 2)) # 2 x 2 x 2 형태의 ndarray 생성
print(arr)
print(arr.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3


In [24]:
arr = np.ones(5)
print(arr)

print('\n')

arr = np.ones((2, 3))
print(arr)

[1. 1. 1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
arr = np.full(5, 2) # 0, 1을 제외한 수를 초기화 할 때 full 사용
print(arr)

print('\n')

arr = np.full((2, 3), -1)
print(arr)

[2 2 2 2 2]


[[-1 -1 -1]
 [-1 -1 -1]]


In [27]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
import numpy as np

arr = np.random.random(5) # 실수 형태의 ndarray 반환
print(arr)

print('\n')

arr = np.random.random((2, 2))
print(arr)

[0.04364843 0.97441015 0.23850292 0.60599822 0.42044599]


[[0.53749008 0.37325703]
 [0.90820201 0.27302308]]
