In [2]:
import numpy as np

arr = np.arange(10)
print(arr)

reshp = arr.reshape(2, 5) # list 형태로 변환 가능
print(reshp)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
arr = np.arange(4, 15)
print(arr)

print(arr[0])

s1 = arr[:5]
print(s1)

s2 = arr[3:10]
print(s2)

[ 4  5  6  7  8  9 10 11 12 13 14]
4
[4 5 6 7 8]
[ 7  8  9 10 11 12 13]


In [9]:
data = [[1, 2, 3],
        [4, 5, 6]]

print(data)
print(type(data))
data[0]
data[0][0]
data[1][1]

[[1, 2, 3], [4, 5, 6]]
<class 'list'>


5

In [15]:
arr = np.array(data)
print(type(arr))

print(arr)

print(arr[0])
print(arr[1])

print(arr[0][0])
print(arr[1, 1])
print(arr[:, 0]) # 모든 row에서 첫번째 column만 가져옴

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
1
5
[1 4]


In [22]:
arr = np.arange(10).reshape(2, 5)
print(arr)

s1 = arr[1, 4]
print(s1)

s2 = arr[1]
print(s2)

s3 = arr[1:5]
print(s3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
9
[5 6 7 8 9]
[[5 6 7 8 9]]
