In [10]:
import pyaudio
import numpy as np

class Tone:
    def __init__(self, volume = .5, rate = 48000, channels = 1):
        self.volume = volume
        self.rate = rate
        self.channels = channels
        self.p = pyaudio.PyAudio()
        self.stream = self.p.open(format = pyaudio.paFloat32, 
                                  channels = self.channels, rate = self.rate, output = True)
        
    def __enter__(self):
        return self
    
    def __exit__(self, type, value, traceback):
        self.stop()
        
    def stop(self):
        self.stream.stop_stream()
        self.stream.close()
        self.p.terminate()
        
    def play(self, octave, note, duration):
        f = 2 ** (octave) * 55 * 2 ** (((note) - 10) / 12)
        sample = (np.sin(2 * np.pi * np.arange(self.rate * duration) * f / self.rate)).astype(np.float32)
        self.stream.write(self.volume * sample)

# 한 개 입력
with Tone() as tone:
    while True:
        i_Tone = int(input("숫자 입력 : "))
        
        if i_Tone == 0: 
            break
            
        else:
            tone.play(3, i_Tone, 4)   

숫자 입력 :  3
숫자 입력 :  0


In [27]:
import pyaudio
import numpy as np

class Tone:
    def __init__(self, volume = .5, rate = 48000, channels = 1):
        self.volume = volume
        self.rate = rate
        self.channels = channels
        self.p = pyaudio.PyAudio()
        self.stream = self.p.open(format = pyaudio.paFloat32, 
                                  channels = self.channels, rate = self.rate, output = True)
        
    def __enter__(self):
        return self
    
    def __exit__(self, type, value, traceback):
        self.stop()
        
    def stop(self):
        self.stream.stop_stream()
        self.stream.close()
        self.p.terminate()
        
    def play(self, octave, notes, duration):
        for note in notes:
            f = 2 ** (octave) * 55 * 2 ** (((note) - 10) / 12)
            sample = (np.sin(2 * np.pi * np.arange(self.rate * duration) * f / self.rate)).astype(np.float32)
            self.stream.write(self.volume * sample)

# 여러 개 입력
with Tone() as tone:
    while True:
        Tone_list = input("숫자 입력 : ").split()
        Tone_list = list(map(int, Tone_list))
        
        if 0 in Tone_list: 
            break
            
        else:
            tone.play(3, Tone_list, 4)

숫자 입력 :  3 2 1 2 3 3 3 2 2 2 3 3 3
숫자 입력 :  0


In [17]:
# 조도 센서 이용

import numpy as np
from pop import Cds, delay

cds = Cds(7)

for i in range(20):
    value = cds.readAverage()
    print(value)
    delay(500)

1216
1216
1216
1215
1213
862
47
48
48
50
51
54
649
506
701
817
80
79
56
57


In [31]:
# 조도 센서 이용하여 RC Car 속도 조정

import numpy as np
import time
from pop import Cds, delay
from pop import Pilot

Car = Pilot.AutoCar()
cds = Cds(7)

for i in range(100):
    value = cds.readAverage()
    
    Car.setSpeed(value / 16)
    Car.forward()
    
    print(value)
    delay(500)

SyntaxError: invalid syntax (<ipython-input-31-622bcbd553e8>, line 15)

In [33]:
import pandas as pd

arr = [1, 2, 3, 4] # python list
type(arr)

s = pd.Series(arr) # series type 객체 변환 -> index와 value 형태로 변환
print(s)
type(s)

0    1
1    2
2    3
3    4
dtype: int64


In [50]:
import pandas as pd

value = [32, 68, 220, 77]
i = ["온도", "습도", "강수량", "불쾌지수"]

sr = pd.Series(value, index)

print(type(sr))

print(sr["온도"]) # index를 통한 접근
print(sr.index)
print(sr.values)
print(sr.iloc[0]) # iloc 행번호로 출력
print(sr.loc['습도']) # loc index로 출력
print(sr.iloc[-1]) # '-1'은 마지막 value에 접근

sr.loc['좋음'] = 0 # 추가
sr2 = sr.drop('좋음') # 삭제

print(sr)
print(sr2)

sr = sr.drop("불쾌지수")
print(sr)

<class 'pandas.core.series.Series'>
32
Index(['온도', '습도', '강수량', '불쾌지수'], dtype='object')
[ 32  68 220  77]
32
68
77
온도       32
습도       68
강수량     220
불쾌지수     77
좋음        0
dtype: int64
온도       32
습도       68
강수량     220
불쾌지수     77
dtype: int64


In [52]:
import pandas as pd

data = [19, 14, 12]
index = ['하나', '둘', '셋']

s = pd.Series(data, index)
print(s)

s['둘'] = 22 # index로 접근하여 수정
print(s)

s.loc['하나'] = 1
print(s)

하나    19
둘     14
셋     12
dtype: int64


In [56]:
from pandas import Series

s = Series([10, 20, 30])
print(s)

print(s + 5)

h = Series([10, 20, 30, 40, 50])
l = Series([1, 2, 3, 4, 5])

diff = (h - l)
print(diff)

cond = diff > 30
print(cond)

0    10
1    20
2    30
dtype: int64
0    15
1    25
2    35
dtype: int64
0     9
1    18
2    27
3    36
4    45
dtype: int64
0    False
1    False
2    False
3     True
4     True
dtype: bool


In [69]:
# 저가와 고가의 차이가 100 이상인 고가 출력
from pandas import Series

up = pd.Series([10, 200, 200, 400, 600])
dp = pd.Series([100, 300, 400, 500, 600])

diff = (dp - up) >= 100

print(diff)

dp[diff] # True인 dp만 출력

0    False
1     True
2     True
3     True
4    False
dtype: bool


1    300
2    400
3    500
dtype: int64

In [80]:
# 종가가 80000원 이상 90000원 미만의 요일을 출력

from pandas import Series

data = [80010, 87100, 77800, 99000, 79900]
day = ['월', '화', '수', '목', '금']

# 종가
종가 = pd.Series(data = data, index = day)

# 조건
cond = (종가 >= 80000) & (종가 < 90000)
print(cond)

종가[cond].index
pd.Series()

월     True
화     True
수    False
목    False
금    False
dtype: bool


Series([], dtype: float64)

In [85]:
import pandas as pd

x = np.arange(4).reshape(2, 2)
print(x)

y = np.arange(3, -1, -1).reshape(2, 2)
print(y)

s1 = np.matmul(x, y) # 2차원 벡터 곱셉
print(s1)

[[0 1]
 [2 3]]
[[3 2]
 [1 0]]
[[1 0]
 [9 4]]


In [87]:
x = np.arange(4).reshape(2, 2)
print(x)

s1 = np.abs(x) # 절대값
print(s1)

s2 = np.square(x) # 제곱
print(s2)

s3 = np.sqrt(x) # 제곱근
print(s3)

s4 = np.log(x) # 로그
print(s4)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[0.         1.        ]
 [1.41421356 1.73205081]]
[[      -inf 0.        ]
 [0.69314718 1.09861229]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in log
  del sys.path[0]


In [88]:
x = np.arange(4).reshape(2, 2)
print(x)

y = np.arange(3, -1, -1).reshape(2, 2)
print(y)

s1 = np.where(x > y, x, y)
print(s1)

[[0 1]
 [2 3]]
[[3 2]
 [1 0]]
[[3 2]
 [2 3]]


In [92]:
import pandas as pd

values = [[32, 68, 220, 72],
         [20, 30, 0, 12],
         [38, 81, 0, 91]]

df = pd.DataFrame(values)

print(df)
df[0][1]

list = [[32, 68, 220, 72],
         [20, 30, 0, 12],
         [38, 81, 0, 91]]

list[0][1]

    0   1    2   3
0  32  68  220  72
1  20  30    0  12
2  38  81    0  91


68

In [118]:
import pandas as pd

values = [[32, 68, 220, 72],
         [20, 30, 0, 12],
         [38, 81, 0, 91]]
colums = ['온도', '습도', '강수량', '불쾌지수']
index = ['초여름', '늦봄', '한여름']

df = pd.DataFrame(values, index, colums)

print(df)
print(df['온도'])
print(df['온도']['늦봄'])

print('\n')

print(df.loc['늦봄'])    # loc : index 접근
print(df.iloc[[1]])     # iloc : 행번호 접근
                        # [] : Series return, [[]] : 행번호 return  

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
한여름  38  81    0    91
초여름    32
늦봄     20
한여름    38
Name: 온도, dtype: int64
20


온도      20
습도      30
강수량      0
불쾌지수    12
Name: 늦봄, dtype: int64
    온도  습도  강수량  불쾌지수
늦봄  20  30    0    12


In [111]:
import pandas as pd

values = [[32, 68, 220, 72],
         [20, 30, 0, 12],
         [38, 81, 0, 91]]
colums = ['온도', '습도', '강수량', '불쾌지수']
index = ['초여름', '늦봄', '한여름']

df = pd.DataFrame(values, index, colums)

print(df)
print(df.index)
print(df.columns)
print(df.values)

df[['온도', '강수량']]

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
한여름  38  81    0    91
Index(['초여름', '늦봄', '한여름'], dtype='object')
Index(['온도', '습도', '강수량', '불쾌지수'], dtype='object')
[[ 32  68 220  72]
 [ 20  30   0  12]
 [ 38  81   0  91]]


온도  강수량
초여름  32  220
늦봄   20    0
한여름  38    0

In [122]:
df.iloc[[0, 1]]
df.loc[['초여름', '늦봄']]

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [123]:
df.iloc[0:2]

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [124]:
df.loc['초여름':'늦봄']

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [127]:
print(df.loc['초여름', '온도'])    # index : 행 x 열
print(df.loc[:, '온도'])          # 전체 행에서 온도만 출력
print(df.loc[:, '습도':'강수량']) 

32
초여름    32
늦봄     20
한여름    38
Name: 온도, dtype: int64
     습도  강수량
초여름  68  220
늦봄   30    0
한여름  81    0


In [135]:
# 온도가 30도 이상인 모든 행 출력

import pandas as pd

values = [[32, 68, 220, 72],
         [20, 30, 0, 12],
         [38, 81, 0, 91]]
colums = ['온도', '습도', '강수량', '불쾌지수']
index = ['초여름', '늦봄', '한여름']

cond = df['온도'] >= 30
print(df[cond])

# df['초여름'] --> 행은 접근 불가능 
df.loc['초여름'] --> 행에 접근하려면 loc 사용

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
한여름  38  81    0    91


온도       32
습도       68
강수량     220
불쾌지수     72
Name: 초여름, dtype: int64